### ISSUE TITLE
error while executing demo_construct_semantic_hierarchy_iaprtc12 

### ISSUE THREAD

**Issue by gargisri68** [wubaoyuan/DIA#2]
The following  command
run('demo/demo_construct_semantic_hierarchy_iaprtc12 .m')

gives the error: 

Error using importdata (line 137)
Unable to open file.

Error in demo_construct_semantic_hierarchy_iaprtc12 (line 205)
class_name = importdata([data_name, '_dictionary.txt']);

Error in run (line 91)
evalin('caller', strcat(script, ';'));

**Comment by wubaoyuan** [comment]
@gargisri68 Thanks for the feedback. Have you unzip the data.zip? iaprtc12_dictionary.txt is included in data folder

**Comment by gargisri68** [comment]
It worked. But now I'm getting the following error:

Reference to non-existent field 'options'.

Error in DIA_inference (line 33)
X = single([feature_matrix'; ones(1, num_instance)./result_struct_Theta_obj.options.biasFactor]);

Error in demo_main (line 15)
test_result_DIA_inference = DIA_inference(data_name, dataset_test, options);

Error in run (line 91)
evalin('caller', strcat(script, ';'));

**Comment by wubaoyuan** [comment]
@gargisri68 Sorry for this typo. Please change Line 33 in DIA_inference to 
"X = single([feature_matrix'; ones(1, num_instance)./result_struct_Theta_obj.params.biasFactor]);"

**Comment by gargisri68** [comment]
For iaprtc12 the code is working fine. But when I execute the code for espgame the following error is observed:

Warning: Variable 'espgame_Theta_bs_1024_lr0_1.00_lrGap_50_lrDec_0.98_moment_0.9_iter_100_decay_0.0001_biasF_80.mat' not found. 
> In DIA_inference (line 28)
  In demo_main (line 15) 
Undefined variable "result_struct_Theta_obj" or class "result_struct_Theta_obj.Theta".

Error in DIA_inference (line 29)
Theta = result_struct_Theta_obj.Theta;

Error in demo_main (line 15)
test_result_DIA_inference = DIA_inference(data_name, dataset_test, options);

**Comment by wubaoyuan** [comment]
@gargisri68 Have you finished the training in "demo_main.m". If finished, it will save a mat result named like 'espgame_Theta_bs_1024_lr0_1.00_lrGap_50_lrDec_0.98_moment_0.9_iter_100_decay_0.0001_biasF_80.mat'

**Comment by gargisri68** [comment]
when i am exceuting demo_main.m with dataset_name='espgame' ; I get the above error. I am sending a screenshot

![image](https://user-images.githubusercontent.com/22957479/45296706-8f25cc00-b520-11e8-8a3f-a177c765b78d.png)

**Comment by wubaoyuan** [comment]
Thanks for the message, please check the mat result is saved correctly. I will also check it tomorrow

**Comment by gargisri68** [comment]
I am attaching the screenshot of the variable espgame_Theta_bs_1024_lr0_1.00_lrGap_50_lrDec_0.98_moment_0.9_iter_100_decay_0.0001_biasF_80.mat

![image](https://user-images.githubusercontent.com/22957479/45337388-5976f680-b5a5-11e8-9ef4-2fa8927ab245.png)

**Comment by wubaoyuan** [comment]
@gargisri68 Can you share the mat result with me? Then I can skip the training procedure, to directly check the inference part. My email is wubaoyuan1987@gmail.com

**Comment by wubaoyuan** [comment]
@gargisri68   Now I get the reason. 
There are two mat files in code/result/espgame. 
So, at Line 27 of "DIA_inference.m",  'Thete_file = dir(['result\', data_name, '\', data_name, '_Theta*']);' 
Thete_file becomes a 2x1 struct. 
Then, at Line 28, you should change 'load(Thete_file.name);' to 'load(Thete_file(2).name);'

Please try it.

**Comment by gargisri68** [comment]
It worked. Thank you.
