### ISSUE TITLE
ESP Game

### ISSUE THREAD

**Issue by wangmengdlut** [wubaoyuan/DIA#3]
Hello, I want to ask about the ESP GAME data set. Where did you get it? If you can, can you give me a copy? I have not found the data set you used on the Internet. Thank you

**Comment by wangmengdlut** [comment]
Is the feature you gave extracted with CNN?
thank you

**Comment by wubaoyuan** [comment]
Yes, it is VGG model. you can find the description in Sec 5.1 from my paper

http://openaccess.thecvf.com/content_cvpr_2017/papers/Wu_Diverse_Image_Annotation_CVPR_2017_paper.pdf


wangmengdlut <notifications@github.com> 于2019年8月28日周三 上午7:19写道：

**Comment by wangmengdlut** [comment]
Thank you.
